# -*- coding: utf-8 -*-
"""Bert fine-tunning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXoMx-1iAnyF_UzwDxzOF3mGovca_mpq
"""

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertTokenizer, DistilBertModel
from sklearn.model_selection import train_test_split
import numpy as np

# Data
texts = [
    # Billing Issues
    "I was charged twice for my order",
    "My refund has not been processed",
    "Wrong amount deducted from my account",
    "I need invoice for my purchase",
    "Payment failed but money was deducted",
    "Discount code not applied to my order",
    "I want to cancel my subscription",
    "Double payment taken from my card",

    # Technical Issues
    "App keeps crashing on my phone",
    "Cannot login to my account",
    "Website is not loading properly",
    "Password reset email not received",
    "My account has been hacked",
    "Error message when placing order",
    "App is very slow and freezing",
    "Cannot update my profile picture",

    # Shipping Issues
    "My order has not arrived yet",
    "Package was delivered damaged",
    "Wrong item was delivered to me",
    "Delivery address needs to be changed",
    "Tracking number is not working",
    "Order shows delivered but not received",
    "Shipment stuck in transit for weeks",
    "Need faster delivery for my order",

    # More Billing Issues
    "Unexpected charge appeared on my statement",
    "Refund amount is incorrect",
    "Subscription renewal happened without notice",
    "Unable to download payment receipt",
    "Card charged even after order cancellation",
    "Billing address cannot be updated",
    "Wallet balance not updated after recharge",
    "Payment confirmation email not received",
    "Tax amount on invoice looks wrong",
    "Money deducted but transaction failed",
    "Auto payment was enabled automatically",
    "EMI option is not working properly",
    "Charged extra delivery fee by mistake",
    "Coupon expired before usage",
    "Cannot remove saved credit card",
    "Monthly bill is higher than expected",

    # More Technical Issues
    "Server is down since morning",
    "App logs out automatically",
    "Unable to upload files",
    "Images are not loading in app",
    "Search function is broken",
    "Notification alerts are delayed",
    "Audio not working during video calls",
    "App update failed to install",
    "Website shows internal server error",
    "My profile data disappeared",
    "Keyboard input is lagging badly",
    "Video keeps buffering continuously",
    "Two factor authentication not working",
    "Unable to connect to WiFi",
    "GPS location is inaccurate",
    "Application freezes during checkout",

    # More Shipping Issues
    "Courier partner lost my package",
    "Delivery was attempted but nobody came",
    "Received incomplete order items",
    "Shipping charges are too high",
    "Estimated delivery date keeps changing",
    "Package arrived very late",
    "Tracking status has not updated",
    "Wrong size product delivered",
    "Need to reschedule my delivery",
    "Item missing from shipment box",
    "Package seal was already opened",
    "Delivery executive was rude",
    "Shipment sent to wrong address",
    "Express delivery took too long",
    "Order still packed and not shipped",
    "International shipment delayed at customs"
]

labels = [
    # Billing = 0
    0,0,0,0,0,0,0,0,

    # Technical = 1
    1,1,1,1,1,1,1,1,

    # Shipping = 2
    2,2,2,2,2,2,2,2,

    # More Billing = 0
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,

    # More Technical = 1
    1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,

    # More Shipping = 2
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2
]
label_names = {0: "Billing", 1: "Technical", 2: "Shipping"}

# Split
X_train, X_val, y_train, y_val = train_test_split(
    texts, labels,
    test_size=0.2,
    random_state=42
)

print(f"Train: {len(X_train)} | Val: {len(X_val)}")
print(len(texts))

tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

class ComplaintDataset(Dataset):
  def __init__(self,texts,labels):
    self.encodings = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=64,
        return_tensors='pt'
    )
    self.labels = labels

  def __len__(self):
    return len(self.labels)

  def __getitem__(self,idx):
    return {
        'input_ids':self.encodings['input_ids'][idx],
        'attention_mask':self.encodings['attention_mask'][idx],
        'label':torch.tensor(self.labels[idx],dtype=torch.long)
    }

train_Dataset = ComplaintDataset(X_train,y_train)
val_Dataset = ComplaintDataset(X_val,y_val)

train_loader = DataLoader(train_Dataset,batch_size=4,shuffle=True)
val_loader = DataLoader(val_Dataset,batch_size=4)

class ComplaintClassifier(nn.Module):
  def __init__(self):
    super().__init__()

    #Load DistilBert
    self.bert = DistilBertModel.from_pretrained('distilbert-base-uncased')

    #Freeze all BERT layers
    for param in self.bert.parameters():
      param.requires_grad = False

    self.classifier = nn.Sequential(
        nn.Linear(768,256),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(256,3)
    )

  def forward(self,input_ids,attention_mask):
    outputs = self.bert(
        input_ids = input_ids,
        attention_mask = attention_mask,
    )
    cls_output = outputs.last_hidden_state[:,0,:]

    logits = self.classifier(cls_output)
    return logits

model = ComplaintClassifier()

total = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
frozen = total - trainable

print(f"Total: {total}")
print(f"Trainable Parameters: {trainable}")
print(f"frozen parameters: {frozen}")

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(
    filter(lambda p:p.requires_grad,model.parameters()),
    lr=0.001
)
def train_epoch():
  model.train()
  total_loss=0
  correct=0

  for batch in train_loader:
    input_ids = batch['input_ids']
    attention_mask = batch['attention_mask']
    labels = batch['label']

    logits = model(input_ids,attention_mask)
    loss = criterion(logits,labels)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    total_loss += loss.item()
    predictions = torch.argmax(logits,dim=1)
    correct += (predictions == labels).sum().item()

  return total_loss/len(train_loader),correct/len(X_train)

def evaluate():
  model.eval()
  correct = 0

  with torch.no_grad():
    for batch in val_loader:
      input_ids = batch['input_ids']
      attention_mask = batch['attention_mask']
      labels = batch['label']

      logits = model(input_ids,attention_mask)
      predictions = torch.argmax(logits,dim=1)
      correct += (predictions==labels).sum().item()
  return correct/len(X_val)

#Train
for epoch in range(20):
    train_loss, train_acc = train_epoch()
    val_acc = evaluate()
    print(f"Epoch {epoch+1:2d} | Loss: {train_loss:.4f} | Train Acc: {train_acc:.2%} | Val Acc: {val_acc:.2%}")

from torch.nn.modules import padding
from IPython.utils import encoding
def predict(texts):
  model.eval()
  encoding = tokenizer(
      texts,
      padding=True,
      truncation=True,
      max_length=64,
      return_tensors='pt'
  )
  with torch.no_grad():
    logits = model(
        encoding['input_ids'],
        encoding['attention_mask']
    )
    probabilities = torch.softmax(logits,dim=1)
    prediction_class = torch.argmax(probabilities).item()
    confidence = probabilities[0][prediction_class].item()

  print(f"Text: {texts}")
  print(f"category: {label_names[prediction_class]} ({confidence:.2%})")

predict("I was charged twice please refund")
predict("my app keeps crashing")
predict("My package has not arrived")

import os

# Create folder if it doesn't exist
os.makedirs('/content/drive/MyDrive/models', exist_ok=True)

# Now save
torch.save(
    model.state_dict(),
    '/content/drive/MyDrive/models/complaint_classifier.pth'
)
print("Saved to Google Drive ✅")

